apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  minReadySeconds: 5
  strategy:
         rollingUpdate:
            maxSurge: 0
            maxUnavailable: 1
         type: RollingUpdate

  replicas: 5
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
       
    spec:
      containers:
      - name: webc
        image: hjain99/profile-page:v2
        ports:
        - containerPort: 80
        
---

apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: webapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
      nodePort: 30001
          
              
